/** Per-module "Sources & References" — transcribed verbatim from the website's Settings
 * page (app.html's `.sources-module` accordions, one per module). The website has no JS
 * data structure for these (they're hand-authored HTML), so this file is the mobile
 * equivalent: one entry per citation, in the same order, with the same wording. Keep this
 * in sync with app.html if the website's citations ever change. */

export type SourceRef = { text: string; domain: string; url: string };

export const MODULE_SOURCES: Record<string, SourceRef[]> = {
  earning: [
    { text: 'FICA payroll tax rate — 7.65% total (6.2% Social Security + 1.45% Medicare). Internal Revenue Service, "Topic no. 751, Social Security and Medicare withholding rates."', domain: 'irs.gov', url: 'https://www.irs.gov/taxtopics/tc751' },
    { text: 'Work-Study earnings are generally exempt from FICA tax while a student is enrolled and regularly attending classes at least half-time. Internal Revenue Service, "Student FICA exception" (26 U.S.C. §3121(b)(10)).', domain: 'irs.gov', url: 'https://www.irs.gov/government-entities/federal-state-local-governments/student-fica-exception' },
    { text: 'A payer must send a 1099-NEC once payments to a contractor reach $2,000 in a calendar year — up from the earlier $600 threshold as of 2026; all income is reportable regardless of whether a form was sent. Internal Revenue Service, "Reporting payments to independent contractors."', domain: 'irs.gov', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/reporting-payments-to-independent-contractors' },
    { text: 'Self-employed individuals generally must make quarterly estimated tax payments if they expect to owe $1,000 or more for the year. Internal Revenue Service, "Self-employment tax (Social Security and Medicare taxes)."', domain: 'irs.gov', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/self-employment-tax-social-security-and-medicare-taxes' },
  ],
  spending: [
    { text: 'The FAFSA opens every year on October 1st. Federal Student Aid, "FAFSA Deadlines."', domain: 'studentaid.gov', url: 'https://studentaid.gov/apply-for-aid/fafsa/fafsa-deadlines' },
    { text: 'A full emergency fund covers roughly 3-6 months of expenses. Consumer Financial Protection Bureau, "An essential guide to building an emergency fund."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/' },
    { text: 'The 50/30/20 budget rule splits after-tax income into roughly 50% needs, 30% wants, and 20% savings/debt repayment. Consumer Financial Protection Bureau, "Money as You Grow: Analyzing budgets."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/teach/activities/analyzing-budgets/' },
    { text: 'The FAFSA uses "prior-prior year" tax information — the 2026-27 FAFSA relies on 2024 tax data, not the most recently filed return. Federal Student Aid, "Why do I have to submit my 2024 tax and income information for the 2026-27 FAFSA form?"', domain: 'studentaid.gov', url: 'https://studentaid.gov/2627/help/why-tax-info' },
  ],
  saving: [
    { text: 'FDIC insurance covers deposits up to $250,000 per depositor, per bank, per ownership category. FDIC, "Understanding Deposit Insurance."', domain: 'fdic.gov', url: 'https://www.fdic.gov/resources/deposit-insurance/understanding-deposit-insurance' },
    { text: 'High-yield savings APYs vs. the near-zero rate on a typical traditional savings account — actual rates move with the market; check current national averages. FDIC, "National Rates and Rate Caps."', domain: 'fdic.gov', url: 'https://www.fdic.gov/national-rates-and-rate-caps' },
    { text: 'Overdraft fees commonly run $30+ per incident. Consumer Financial Protection Bureau, "Data Spotlight: Consumer experiences with overdraft programs."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/data-research/research-reports/data-spotlight-consumer-experiences-with-overdraft-programs/full-report/' },
    { text: 'A full emergency fund covers roughly 3-6 months of expenses. Consumer Financial Protection Bureau, "An essential guide to building an emergency fund."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/' },
    { text: 'A $500 starter emergency fund is a commonly recommended first target before working toward the full 3-6 month goal. NerdWallet, "Emergency Fund: What it Is and Why it Matters."', domain: 'nerdwallet.com', url: 'https://www.nerdwallet.com/banking/learn/emergency-fund-why-it-matters' },
    { text: 'Which banks lead on high-yield savings APYs changes often with the rate environment — check current listings rather than a fixed number or bank name. NerdWallet, "Best High-Yield Savings Accounts."', domain: 'nerdwallet.com', url: 'https://www.nerdwallet.com/banking/best/high-yield-online-savings-accounts' },
  ],
  investing: [
    { text: 'Roth IRA annual contribution limit set by the IRS. Internal Revenue Service, "Retirement topics - IRA contribution limits."', domain: 'irs.gov', url: 'https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-ira-contribution-limits' },
    { text: 'Roth IRA eligibility is based on having earned income, not age or job type. Internal Revenue Service, Publication 590-A.', domain: 'irs.gov', url: 'https://www.irs.gov/publications/p590a' },
    { text: 'Long-run stock market returns average roughly 7%/year after inflation — a commonly-cited historical average that varies by source, time period, and methodology. "S&P 500 Historical Annual Returns (1927-2026)."', domain: 'macrotrends.net', url: 'https://www.macrotrends.net/2526/sp-500-historical-annual-returns' },
    { text: 'Major brokerages including Fidelity, Schwab, and Vanguard offer $0 account minimums and $0 commission on stock/ETF trades. Fidelity, "Straightforward and Transparent Pricing."', domain: 'fidelity.com', url: 'https://www.fidelity.com/why-fidelity/pricing-fees' },
    { text: 'Withdrawing Roth IRA/401(k) earnings before age 59½ generally triggers a 10% additional tax, though withdrawing your own Roth contributions does not. Internal Revenue Service, "Retirement topics - Exceptions to tax on early distributions."', domain: 'irs.gov', url: 'https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-exceptions-to-tax-on-early-distributions' },
    { text: 'The "Rule of 72" estimates years to double an investment by dividing 72 by the annual rate of return. U.S. Securities and Exchange Commission, Investor.gov compound interest calculator.', domain: 'investor.gov', url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator' },
  ],
  credit: [
    { text: 'FICO scores range 300-850; 670+ is "Good," 740+ is "Very Good," 800+ is "Exceptional." myFICO, "What is a Credit Score?"', domain: 'myfico.com', url: 'https://www.myfico.com/credit-education/credit-scores' },
    { text: 'FICO score factor weights: payment history 35%, amounts owed 30%, length of history 15%, new credit 10%, credit mix 10%. myFICO, "How are FICO Scores Calculated?"', domain: 'myfico.com', url: 'https://www.myfico.com/credit-education/whats-in-your-credit-score' },
    { text: 'The three nationwide credit bureaus are Equifax, Experian, and TransUnion; free reports at AnnualCreditReport.com. FTC, "Free Credit Reports."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/free-credit-reports' },
    { text: 'Hard inquiries can stay on a credit report for up to two years. Consumer Financial Protection Bureau, "What is a credit inquiry?"', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-inquiry-en-1317/' },
    { text: 'Rate-shopping inquiries made within a 14-45 day window count as a single inquiry for scoring purposes. myFICO, "How to Rate Shop and Minimize the Impact to Your FICO Scores."', domain: 'myfico.com', url: 'https://www.myfico.com/credit-education/blog/rate-shop' },
    { text: 'Payday loans commonly carry APRs around 300-400%. Consumer Financial Protection Bureau, "What is an APR ... for my payday loan?"', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-an-annual-percentage-rate-apr-and-why-is-it-higher-than-the-interest-rate-for-my-payday-loan-en-1625/' },
    { text: 'Retail/store credit cards commonly carry APRs of 25-30%+, notably higher than general-purpose cards. Consumer Financial Protection Bureau, "Issue Spotlight: The High Cost of Retail Credit Cards."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/data-research/research-reports/issue-spotlight-the-high-cost-of-retail-credit-cards/' },
    { text: 'Balance transfer fees commonly run 3-5% of the amount transferred. Experian, "What Is a Balance Transfer Fee?"', domain: 'experian.com', url: 'https://www.experian.com/blogs/ask-experian/what-is-a-balance-transfer-fee/' },
    { text: 'Secured credit cards typically require a refundable deposit, often starting around $200. Bankrate, "How Much Is A Secured Credit Card Deposit?"', domain: 'bankrate.com', url: 'https://www.bankrate.com/credit-cards/building-credit/secured-card-deposit-amount/' },
    { text: 'Credit bureaus are generally required to investigate a dispute within 30 days, at no cost to you. Consumer Financial Protection Bureau, "How long does it take to repair an error on a credit report?"', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/ask-cfpb/how-long-does-it-take-to-repair-an-error-on-a-credit-report-en-1339/' },
  ],
  risk: [
    { text: "Under the ACA, young adults can generally stay on a parent's health plan until age 26. HealthCare.gov, \"Health Insurance Coverage For Children and Young Adults Under 26.\"", domain: 'healthcare.gov', url: 'https://www.healthcare.gov/young-adults/children-under-26/' },
    { text: 'Federal law (Regulation E) caps your liability for unauthorized debit card charges at $50 if reported within 2 business days, $500 if reported later, unlimited after 60 days. Consumer Financial Protection Bureau, "Sec. 1005.6 Liability of consumer for unauthorized transfers."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/rules-policy/regulations/1005/6/' },
    { text: 'Renters insurance averages roughly $10-20/month nationally. NerdWallet, "How Much Is Renters Insurance?"', domain: 'nerdwallet.com', url: 'https://www.nerdwallet.com/insurance/renters/learn/how-much-is-renters-insurance' },
    { text: 'Auto and renters/homeowners liability coverage caps out at a maximum payout, often in the $100,000-$300,000 range depending on the policy. Insurance Information Institute, "Renters Insurance."', domain: 'iii.org', url: 'https://www.iii.org/article/renters-insurance' },
    { text: 'Auto liability insurance is legally required in nearly every state. Insurance Information Institute, "Background on: Compulsory Auto/Uninsured Motorists."', domain: 'iii.org', url: 'https://www.iii.org/article/background-on-compulsory-auto-uninsured-motorists' },
    { text: 'A $1,000,000 umbrella policy commonly costs around $200-$400/year on top of existing coverage. NerdWallet, "Umbrella Insurance: Coverage & How It Works."', domain: 'nerdwallet.com', url: 'https://www.nerdwallet.com/insurance/homeowners/learn/umbrella-insurance' },
  ],
  loans: [
    { text: "The government pays interest on Direct Subsidized Loans while you're enrolled at least half-time; Unsubsidized loans accrue interest from disbursement. Federal Student Aid, \"Subsidized and Unsubsidized Loans.\"", domain: 'studentaid.gov', url: 'https://studentaid.gov/understand-aid/types/loans/subsidized-unsubsidized' },
    { text: 'A 6-month grace period applies after graduating or dropping below half-time enrollment before federal loan payments begin. Federal Student Aid, "How Long Is My Grace Period."', domain: 'studentaid.gov', url: 'https://studentaid.gov/help-center/answers/article/how-long-is-my-grace-period' },
    { text: 'A Master Promissory Note and entrance counseling are required before your first federal loan disbursement. Federal Student Aid, Master Promissory Note (Direct Subsidized/Unsubsidized).', domain: 'studentaid.gov', url: 'https://studentaid.gov/sites/default/files/MasterPromissoryNoteMPNDirectSubsidizedLoansandDirectUnsubsidizedLoans-en-us.pdf' },
    { text: 'Federal loans default to the Standard Repayment Plan — a fixed 10-year schedule for loans first disbursed before July 1, 2026, or a tiered 10-25 year schedule based on balance for loans disbursed on or after that date. Federal Student Aid, "Federal Student Loan Repayment Plans."', domain: 'studentaid.gov', url: 'https://studentaid.gov/manage-loans/repayment/plans' },
    { text: "Parent PLUS Loans require a credit check and legally cannot be transferred into the student's name. Federal Student Aid, \"Parent PLUS Loans\"; Consumer Financial Protection Bureau, \"Options for repaying your Parent PLUS loans.\"", domain: 'studentaid.gov', url: 'https://studentaid.gov/understand-aid/types/loans/plus/parent' },
    { text: 'Half-time enrollment for undergrads is commonly around 6 credits per semester, though each school sets its own exact threshold. Federal Student Aid, "Half-Time Enrollment."', domain: 'studentaid.gov', url: 'https://studentaid.gov/help-center/answers/article/half-time-enrollment' },
    { text: 'Starting July 1, 2026, Grad PLUS Loans were discontinued for new borrowers; graduate students now borrow through higher Direct Unsubsidized Loan limits instead ($20,500/year, $100,000 lifetime; $50,000/year, $200,000 lifetime for select professional-degree programs). Federal Student Aid, "Big Updates to Federal Student Aid."', domain: 'studentaid.gov', url: 'https://studentaid.gov/announcements-events/big-updates' },
    { text: "Interest that accrues during a deferment or forbearance is generally added to (capitalized into) the loan's principal once that period ends. Federal Student Aid, \"What is capitalized interest?\"", domain: 'studentaid.gov', url: 'https://studentaid.gov/help-center/answers/article/what-is-loan-capitalized-interest' },
    { text: 'Enrolling in autopay on a federal student loan generally comes with an interest rate reduction. Federal Student Aid, "Auto Pay Interest Rate Reduction."', domain: 'studentaid.gov', url: 'https://studentaid.gov/announcements-events/auto-pay-interest-rate-reduction' },
  ],
  taxes: [
    { text: 'The federal individual tax filing deadline is typically April 15th. Internal Revenue Service, "Filing."', domain: 'irs.gov', url: 'https://www.irs.gov/filing' },
    { text: 'American Opportunity Tax Credit — up to $2,500/year, up to 40% ($1,000) refundable, first four years of postsecondary education. Internal Revenue Service, "Education credits - AOTC and LLC."', domain: 'irs.gov', url: 'https://www.irs.gov/credits-deductions/individuals/education-credits-aotc-and-llc' },
    { text: 'Lifetime Learning Credit — up to $2,000/year (20% of up to $10,000 in expenses), no limit on number of years claimed. Internal Revenue Service, "Education credits - AOTC and LLC."', domain: 'irs.gov', url: 'https://www.irs.gov/credits-deductions/individuals/education-credits-aotc-and-llc' },
    { text: 'Self-employment tax is 15.3%, owed once net self-employment earnings reach $400; estimated quarterly payments are generally required if you expect to owe $1,000+ for the year. Internal Revenue Service, "Self-employment tax (Social Security and Medicare taxes)."', domain: 'irs.gov', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/self-employment-tax-social-security-and-medicare-taxes' },
    { text: 'Form 1098-T reports tuition paid and scholarships/grants received, used to help calculate education credits. Internal Revenue Service, "About Form 1098-T."', domain: 'irs.gov', url: 'https://www.irs.gov/forms-pubs/about-form-1098-t' },
    { text: 'Combined with direct deposit, the IRS issues most e-filed refunds in less than 21 days. Internal Revenue Service, "Direct deposit fastest way to receive federal tax refund."', domain: 'irs.gov', url: 'https://www.irs.gov/newsroom/direct-deposit-fastest-way-to-receive-federal-tax-refund' },
    { text: 'Quarterly estimated tax payments are generally due in mid-April, June, September, and January. Internal Revenue Service, "Estimated Taxes."', domain: 'irs.gov', url: 'https://www.irs.gov/faqs/estimated-tax' },
    { text: 'A filing extension only extends the deadline to file a return — any tax owed is still due by the original deadline. Internal Revenue Service, "Need more time to file? Don\'t wait, request an extension."', domain: 'irs.gov', url: 'https://www.irs.gov/newsroom/need-more-time-to-file-dont-wait-request-an-extension' },
    { text: 'A Form W-4 can be updated with an employer at any time to adjust paycheck withholding. Internal Revenue Service, "About Form W-4."', domain: 'irs.gov', url: 'https://www.irs.gov/forms-pubs/about-form-w-4' },
    { text: 'IRS Free File and free VITA tax-prep clinics are legitimate no-cost filing options for qualifying taxpayers. Internal Revenue Service, "IRS Free File."', domain: 'irs.gov', url: 'https://www.irs.gov/filing/free-file-do-your-federal-taxes-for-free' },
    { text: "The U.S. uses a progressive, marginal tax bracket system — only income within a given bracket is taxed at that bracket's rate. Internal Revenue Service, \"Federal income tax rates and brackets.\"", domain: 'irs.gov', url: 'https://www.irs.gov/filing/federal-income-tax-rates-and-brackets' },
  ],
  psychology: [
    { text: 'Mental accounting — the tendency to treat money differently based on its source or intended use, even though a dollar spends the same regardless. Richard Thaler, "Mental Accounting Matters" (1999); overview via The Decision Lab.', domain: 'thedecisionlab.com', url: 'https://thedecisionlab.com/reference-guide/psychology/mental-accounting' },
    { text: "The sunk cost fallacy — the tendency to keep investing in something because of what's already been spent, rather than its future value. The Decision Lab, \"The Sunk Cost Fallacy.\"", domain: 'thedecisionlab.com', url: 'https://thedecisionlab.com/biases/the-sunk-cost-fallacy' },
    { text: 'A scarcity mindset — feeling short on money or time narrows attention onto the immediate problem and can worsen decision-making on other tradeoffs. Mullainathan & Shafir, "Scarcity: Why Having Too Little Means So Much"; summary via Harvard Kennedy School Center for International Development.', domain: 'hks.harvard.edu', url: 'https://www.hks.harvard.edu/centers/cid/publications/books/scarcity-why-having-too-little-means-so-much' },
    { text: 'Missed Buy Now, Pay Later payments can, depending on the provider, be reported to credit bureaus and affect a credit score. Consumer Financial Protection Bureau, "Buy Now, Pay Later and Credit Reporting."', domain: 'consumerfinance.gov', url: 'https://www.consumerfinance.gov/about-us/blog/by-now-pay-later-and-credit-reporting/' },
  ],
  career: [
    { text: "Job switchers and job stayers see different wage growth, and the size of that gap shifts with the labor market over time — it's not a fixed, guaranteed spread. Federal Reserve Bank of Atlanta, \"Wage Growth Tracker.\"", domain: 'atlantafed.org', url: 'https://www.atlantafed.org/research-and-data/data/wage-growth-tracker' },
    { text: 'Research tracing to sociologist Mark Granovetter\'s studies on job-seeking puts the share of workers who found their job through a personal contact at roughly 30-60%, notably lower than some inflated career-advice figures. Granovetter, "Getting a Job: A Study of Contacts and Careers"; summarized via NIH Office of Intramural Training & Education, "Networking: The Strength of Weak Ties."', domain: 'training.nih.gov', url: 'https://www.training.nih.gov/oite-careers-blog/networking-the-strength-of-weak-ties/' },
    { text: 'An employer 401(k) match is often described as one of the closest things to a guaranteed, risk-free return available to an investor. NerdWallet, "What Is a 401(k) Match?"', domain: 'nerdwallet.com', url: 'https://www.nerdwallet.com/article/investing/401k-match' },
  ],
  scams: [
    { text: 'Credit freezes are free by federal law and must be requested separately with each of the three bureaus. FTC, "Credit Freezes and Fraud Alerts."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/credit-freezes-and-fraud-alerts' },
    { text: "IdentityTheft.gov is the FTC's official site for reporting identity theft and building a personal recovery plan. Federal Trade Commission.", domain: 'identitytheft.gov', url: 'https://www.identitytheft.gov' },
    { text: ".gov domains are restricted to verified government organizations and can't be purchased by anyone else. General Services Administration, \"Eligibility for .gov domains.\"", domain: 'get.gov', url: 'https://get.gov/domains/eligibility/' },
    { text: 'P2P payment apps like Venmo, Cash App, and Zelle are built for paying people you already trust, and generally offer no fraud dispute process once a payment is sent, unlike a credit card. FTC, "Do you use payment apps like Venmo, CashApp, or Zelle? Read this."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/consumer-alerts/2023/08/do-you-use-payment-apps-venmo-cashapp-or-zelle-read' },
    { text: "A credit card chargeback lets you dispute a charge with your card issuer if an order never arrives or isn't as described. FTC, \"Using Credit Cards and Disputing Charges.\"", domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/using-credit-cards-and-disputing-charges' },
    { text: "Gift card and wire transfer payments generally can't be reversed once sent, which is why scammers favor them. FTC, \"Avoiding and Reporting Gift Card Scams.\"", domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/avoiding-and-reporting-gift-card-scams' },
    { text: 'Banks must generally make deposited funds available within a few business days, but a fraudulent check can take weeks to actually bounce, letting fake-check scams look "cleared" before the fraud surfaces. FTC, "How To Spot, Avoid, and Report Fake Check Scams."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/how-spot-avoid-and-report-fake-check-scams' },
    { text: 'Legitimate scholarships never require paying a fee to receive an award. FTC, "How To Avoid Scholarship and Financial Aid Scams."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/how-avoid-scholarship-and-financial-aid-scams' },
    { text: 'Real companies do not proactively pop up a warning or cold-call telling you to call them about a virus. FTC, "How To Spot, Avoid, and Report Tech Support Scams."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/how-spot-avoid-and-report-tech-support-scams' },
    { text: 'Romance scams typically ask for money via gift cards, wire transfers, or cryptocurrency — payment methods that are hard to trace or reverse. FTC, "What To Know About Romance Scams."', domain: 'consumer.ftc.gov', url: 'https://consumer.ftc.gov/articles/what-know-about-romance-scams' },
  ],
};
